// Builds the committed web assets in src/latexblocks/assets/ from the
// library's OWN frontend source. No third-party code is bundled: the two
// entry modules (tooltip-system, label-copy) have zero imports.
import esbuild from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, readdirSync } from 'node:fs';
import postcss from 'postcss';
import postcssNesting from 'postcss-nesting';
import postcssCustomMedia from 'postcss-custom-media';
import postcssLab from 'postcss-lab-function';
import autoprefixer from 'autoprefixer';

// Browser bundle (iife: plain <script defer> tag, no module semantics needed)
await esbuild.build({
  entryPoints: ['frontend/src/index.ts'],
  bundle: true,
  format: 'iife',
  target: 'es2020',
  minify: true,
  outfile: 'src/latexblocks/assets/latexblocks.js',
  banner: { js: '// GENERATED by build.mjs from frontend/src/ — do not edit.' },
});

// CSS through the same PostCSS pipeline mathnotes uses
const css = readFileSync('frontend/css/latexblocks.css', 'utf8');
const result = await postcss([
  postcssNesting, postcssCustomMedia, postcssLab({ preserve: true }), autoprefixer,
]).process(css, { from: 'frontend/css/latexblocks.css' });
writeFileSync('src/latexblocks/assets/latexblocks.css',
  '/* GENERATED by build.mjs from frontend/css/ — do not edit. */\n' + result.css);

// Fonts
mkdirSync('src/latexblocks/assets/fonts', { recursive: true });
for (const f of readdirSync('frontend/fonts')) {
  copyFileSync(`frontend/fonts/${f}`, `src/latexblocks/assets/fonts/${f}`);
}
console.log('built assets/latexblocks.js, assets/latexblocks.css, assets/fonts/');
